### PR TITLE
Added siren trigger functionality to cameras

### PR DESCRIPTION
**Pull request by Speedbreaker12**
Added siren trigger functionality to cameras

### CODE REVIEW

**Review by mcm1957 — COMMENTED** [review]
Please do NOT add concrete versions to README.m dbut use header **WORK IN PROGRESS**. README.md will be updated during release process.

**Review by mcm1957 — CHANGES_REQUESTED** [review]
Please remove concrete version and use generic header **WORK IN PROGRESS**

**Review by mcm1957 — CHANGES_REQUESTED** [review]
Please remove concrete version and use generic header **WORK IN PROGRESS**

**Comment by mcm1957** [comment]
Do NOT add news sectoion to io-package.json and do NOT change version numbers at io-package.json and package.json. Version numbers will be updated by release scripz

**Comment by Speedbreaker12** [comment]
> Do NOT add news sectoion to io-package.json and do NOT change version numbers at io-package.json and package.json. Version numbers will be updated by release scripz

sorry, first time helping with a community adapter! Should be fixed now!

**Comment by theimo1221** [comment]
Will look at it later this evening👍️

**Pull request closed without merging**
